#ifndef RESPONSE_CODES_H
#define RESPONSE_CODES_H

#define OK 0
#define ERR_GENERIC 1
#define ERR_PERMISSION 2
#define ERR_FILE_NOT_FOUND 3
#define ERR_INVALID_ROLE 4
#define ERR_PARSE 5
#define ERR_USER_EXSISTS 6
#define ERR_FILE_OPEN_FAIL 7
#define ERR_INCOMPLETE_TRANSFER 8
#define ERR_TAG_NOT_FOUND 9
#define ERR_TAG_PARSE_FAIL 10
#define ERR_RESPONSE_RECV_FAIL 11
#define ERR_UNKNOWN_COMMAND 12

#endif
